### ISSUE TITLE
Add custom hooks

### ISSUE THREAD

**Issue by TenshiLyle** [CodingAvenue/ca-school-renderer#58]
User of the render should be able to apply their own post rendering routines via a hook.

 * command line option will be `--custom-rendering`
 * Should pass a `vinyl-fs` instance on each course chapter.
 * Will do this during the `post-rendering` task, before we return.

**Comment by TenshiLyle** [comment]
@sandaemc FYI

**Comment by TenshiLyle** [comment]
@sandaemc On our use case, who is going to use this feature? The platform?

**Comment by sandaemc** [comment]
Reader

**Comment by TenshiLyle** [comment]
@sandaemc I have a minor issue on loading the external JS file, it requires a full path for `require` to be able to find it. `process.cwd()` gives me the path that I expect. Still finding out why it cannot find it. Let me know if you want to try it using full path for now.

**Comment by TenshiLyle** [comment]
PR: https://github.com/CodingAvenue/ca-school-renderer/pull/59
