### ISSUE TITLE
section token

### ISSUE THREAD

**Issue by TenshiLyle** [CodingAvenue/ca-school-renderer#65]
* A section token requires multiple children
 * A header token is part of the section children and must be required
 * REPL will be part of the section header with children also.

**Comment by TenshiLyle** [comment]
@sandaemc please confirm. Also what about an REPL with one question only? Do we need to enclose them within a section?

**Comment by sandaemc** [comment]
Here's the structure:

MD structure

```
# Header

## Finding and Fixing Errors

REPL

Question

Question
```

JSON

```
{
   content '<h2>Finding and fixing errors</h2>,
   type: 'Section',
   children: [
     {
       content,
       type: 'REPL', 
       children: [
         {
           content,
           type: 'SS',
           choices: []
       ]
   ]
}
```

**Comment by sandaemc** [comment]
If REPL is not defined to be under section then don't enclose it.

**Comment by TenshiLyle** [comment]
@sandaemc what do you mean by close it? Meaning empty child on the section?

Another question, can a section have other type aside from REPL on the children?

**Comment by sandaemc** [comment]
That's possible. But I think the content writers should follow some patterns. We should enforce patterns.

**Comment by TenshiLyle** [comment]
What do you mean not under REPL?
